#!/usr/bin/env python3

import sys

# My modules
import api
import utils


def usage(name):
    print(f'Usage: {name} <args> <stuff>')
    print('\t-b\t\tGet buildid from version')
    print('\t-d\t\tDownload an ipsw')
    print('\t-k\t\tGrab Keys')
    print('\t-s\t\tSplit KBAG key')
    print('\t-x\t\tExtract IPSW')


if __name__ == '__main__':
    argv = sys.argv
    if len(argv) == 1:
        usage(argv[0])

    if len(argv) > 4:
        sys.exit('We are expecting two arguments but a max of 3!')

    if '-b' in argv:
        print(api.versionToBuildid(argv[2], argv[3]))  # ./yeet -b device version

    elif '-k' in argv:
        api.grabKeys(argv[2], argv[3])  # ./yeet -k device version

    elif '-d' in argv:
        api.downloadIPSW(argv[2], argv[3])  # ./yeet -d device version

    elif '-s' in argv:
        utils.splitKbag(argv[2])  # ./yeet -s KBAG

    elif '-x' in argv:
        utils.extractIPSW(argv[2])  # ./yeet -x IPSW
